### ISSUE TITLE
How do I get the URL for playback of an item?

### ISSUE THREAD

**Issue by Inrego** [MediaBrowser/Emby.ApiClient#37]
Hello.

I am developing an app using this library. I got Browsing figured out, but after having searched for about an hour through the api, I cannot for the life of me figure out how to get a stream or url for playback of an item. Can you provide a sample?
Or do I have to build my own url following this (as in there's no built-in functionality in the library): https://github.com/MediaBrowser/Emby/wiki/Audio-Streaming

**Comment by LukePulverenti** [comment]
Yes you have to build your own urls. Audio is very easy and the link you quoted has an example. Does that help?

**Comment by Inrego** [comment]
Yes I tried the sample, and it works for me. I thought I was going crazy when I couldn't find methods to build the URL in the API. Maybe a quick mention of that on the readme.md would be helpful for others :)
